// Gallery Ledger design: category-led portfolio archive with tactile image cards and editorial case notes.
import { useState } from "react";
import { ArrowUpRight, X } from "lucide-react";
import { Link } from "wouter";
import SiteLayout from "@/components/SiteLayout";
import { CtaBand, PageHero } from "@/components/PagePrimitives";
const projects = [{ title: "A day worth remembering", category: "Events", type: "Event videography", image: "/manus-storage/uem-studio_87419fb9.jpg", note: "Cinematic event coverage with a highlight film and social cutdowns." }, { title: "Form / Function", category: "Corporate", type: "Brand visuals", image: "/manus-storage/uem-architecture_7c35b6b6.jpg", note: "A visual system built to make a considered brand feel immediate." }, { title: "The night carries", category: "Music Videos", type: "Music video", image: "/manus-storage/uem-hero_d0993f40.jpg", note: "Performance-led visuals shaped around rhythm, movement, and atmosphere." }, { title: "In the frame", category: "Photography", type: "Portrait photography", image: "/manus-storage/uem-studio_87419fb9.jpg", note: "Portraits with a little room for personality to come through." }, { title: "From above", category: "Drone", type: "Aerial coverage", image: "/manus-storage/uem-architecture_7c35b6b6.jpg", note: "A wider view for spaces, celebrations, and the scale of the moment." }, { title: "Made to move", category: "Corporate", type: "Social content", image: "/manus-storage/uem-hero_d0993f40.jpg", note: "A short-form package designed for reels, TikTok, and YouTube Shorts." }];
const categories = ["All", "Events", "Corporate", "Music Videos", "Drone", "Photography"];
export default function Portfolio() { const [active, setActive] = useState("All"); const [selected, setSelected] = useState<(typeof projects)[number] | null>(null); const filtered = active === "All" ? projects : projects.filter((p) => p.category === active); return <SiteLayout><PageHero eyebrow="Portfolio / 01" title={<>Proof of<br /><em>perspective.</em></>} intro="A selection of event, brand, music, and social work. More stories are always in motion." /><section className="portfolio-section"><div className="filter-bar">{categories.map((category) => <button className={active === category ? "active" : ""} onClick={() => setActive(category)} key={category}>{category}</button>)}</div><div className="portfolio-grid">{filtered.map((project) => <button className="portfolio-card" key={project.title} onClick={() => setSelected(project)}><div className="portfolio-image"><img src={project.image} alt="" /><span>{project.category}</span></div><div className="portfolio-meta"><p>{project.type}</p><ArrowUpRight size={17} /></div><h3>{project.title}</h3></button>)}</div></section>{selected && <div className="project-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close project"><X size={22} /></button><img src={selected.image} alt="" /><div><p className="eyebrow">{selected.category} / {selected.type}</p><h2>{selected.title}</h2><p>{selected.note}</p><Link className="text-link" href="/contact">Ask about a similar project <ArrowUpRight size={17} /></Link></div></div>}<CtaBand title={<>Your project<br /><em>could be next.</em></>} /></SiteLayout>; }
